POST https://localhost:5001/api/records/add
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwidW5pcXVlX25hbWUiOiJleGFtcGxlMkBnbWFpbC5jb20iLCJuYmYiOjE3MDA2NTMyNzcsImV4cCI6MTcwMTI1ODA3NywiaWF0IjoxNzAwNjUzMjc3fQ._nixyiMxW1x7aPl4Pi4pK3_lxA-umoB4v7ICvyrmOp1G0oFKCMqgsIxb_rtWeegoEz5K558dzsEhbtTAG7aFWA
Content-Type: application/json

{
  

    "name": "payment",
    "description": "",
    "recordtype": "2",
    "category": "salary",
    "price": "2500",
    "date": "2022-09-24T18:25:43.511Z",
    "id": 0
}