DELETE https://localhost:5001/api/user/delete
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI1IiwidW5pcXVlX25hbWUiOiJ0ZXN0NEBtYWlsLnJ1IiwibmJmIjoxNjk5MzUzMzIxLCJleHAiOjE2OTk5NTgxMjEsImlhdCI6MTY5OTM1MzMyMX0.5sCpotJQ5z0W6hxprbUackD3gfRrLOkmaKR_i33vbNh5NRPUgT6qT8Q40ZjYCtg_Yh3X0NL-7uVYuT5hiyDhww
Content-Type: application/json
