DELETE https://localhost:5001/api/account
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzIiwidW5pcXVlX25hbWUiOiJleGFtcGxlM0BnbWFpbC5jb20iLCJuYmYiOjE3MDA2NTAwMjIsImV4cCI6MTcwMTI1NDgyMiwiaWF0IjoxNzAwNjUwMDIyfQ.Lx1qPQsAR4tkhE9inBdSCiQGu4Rvkbt0ye2Js_7BvSNFpgJlCHWjypJAyCZ5YvgjfFnUQFopVEcUa1bXWWgXRA

Content-Type: application/json
