GET https://localhost:5001/api/records?recordtype=1&MaxDate=2024/01&itemsPerPage=16&pageNumber=1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJleGFtcGxlMUBnbWFpbC5jb20iLCJuYmYiOjE2OTgwNTc3NjgsImV4cCI6MTY5ODY2MjU2OCwiaWF0IjoxNjk4MDU3NzY4fQ.XanZ5r5I3aEEsMXn0bHkGEiOvYhI-cGW2HOLoG591nGJrgOTjb52gVEEse-hrKWFBP1kgUs4_7TabKDPhc01cA
Content-Type: application/json
