GET https://localhost:5001/api/records/
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJleGFtcGxlMUBnbWFpbC5jb20iLCJuYmYiOjE3MDI5MTM0MDQsImV4cCI6MTcwMzUxODIwNCwiaWF0IjoxNzAyOTEzNDA0fQ.a5E4VCcaDsxeLJRTkV5xqJA2Za8c-l6tJLBw_NOHCx2p9rYI00flbb-EDpXwU06XfooOlLAi4dlq1hbTcZCeUQ
Content-Type: application/json
